### ISSUE TITLE
nyxx 4.0.0

### ISSUE THREAD

**Issue by SiongSng** [nyxx-discord/nyxx_commander#5]

**Comment by abitofevrything** [comment]
`nyxx_commander` is in the process of being deprecated. Please migrate to [`nyxx_commands`](https://pub.dev/packages/nyxx_commands) which supports the latest nyxx versions and is not dependant on the message content intent.

If you want to continue using `nyxx_commander` regardless, you can use [dependency overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides) to force your bot to use the latest version of `nyxx`.

**Comment by SiongSng** [comment]
Thanks
